# manifests/app/02-secret.yaml

apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskapp
type: Opaque
stringData:
  POSTGRES_USER: "CHANGEME"
  POSTGRES_PASSWORD: "CHANGEME"
  POSTGRES_DB: "taskapp"
  SECRET_KEY: "CHANGEME"
